include:
    - path:
        - alt-routing-demo/compose.yml
    - path:
        - services/compose.yml
    - path:
        - tunnelProxy/compose.yml

services:
    nginx-proxy:
        image: nginxproxy/nginx-proxy
        profiles: [prod]
        labels: 
            - com.github.nginx-proxy.nginx
        ports:
            - 80:80
            - 443:443
        environment:
            ENABLE_IPV6: true
        networks:
            proxy:
            www:
        volumes:
            - html:/usr/share/nginx/html
            - certs:/etc/nginx/certs
            - /var/run/docker.sock:/tmp/docker.sock:ro 
    acme:
        image: nginxproxy/acme-companion
        profiles: [prod]
        volumes:
            - html:/usr/share/nginx/html
            - certs:/etc/nginx/certs
            - acme:/etc/acme.sh
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            DEFAULT_EMAIL: contact@sombrepigeon.fr
        depends_on:
            nginx-proxy:
                condition: service_started
        networks:
            - proxy
            - www

    alt-routing-demo.firefox:
        image: jlesage/firefox
        profiles: [firefox]
        environment:
            VIRTUAL_HOST: firefox.alt-routing-demo.localhost
            VIRTUAL_PORT: 5800
            LANG: fr_FR.UTF-8
            DARK_MODE: 1
            FF_OPEN_URL: alt-routing-demo.sombrepigeon.fr
        ports:
            - 5800:5800
        configs:
            -   source: alt-routing-demo.firefox.userPref
                target: /config/profile/user.js
        networks:
            proxy:
            www:
    alt-routing-demo.chromium:
        image: jlesage/chromium
        profiles: [chromium]
        environment:
            VIRTUAL_HOST: chromium.alt-routing-demo.localhost
            VIRTUAL_PORT: 5801
            LANG: fr_FR.UTF-8
            DARK_MODE: 1
            CHROMIUM_APP_URL: alt-routing-demo.sombrepigeon.fr
        ports:
            - 5801:5800
        networks:
            proxy:
            www:


configs:
    alt-routing-demo.firefox.userPref:
        content: user_pref("dom.securecontext.allowlist", 
                "alt-routing-demo.sombrepigeon.fr,
                alt-routing.dev.releases.sombrepigeon.fr,
                spellbook.alt-routing-demo.sombrepigeon.fr");
            user_pref("devtools.serviceWorkers.testing.enabled", true);
            user_pref("devtools.toolbox.host", "right");
            user_pref("devtools.toolbox.previousHost", "right");
            user_pref("dom.serviceWorkers.testing.enabled", true);
            user_pref("dom.viewTransitions.enabled", true);
            user_pref("layout.css.module-scripts.enabled", true);
            user_pref("devtools.cache.disabled", true);
            user_pref("dom.navigation.webidl.enabled", true);

        
volumes:
    html:
    certs:
    acme:


networks:
    proxy:
        internal: true
    www:
    tunnel_proxy:
        #internal: true