version: '2'

services:
    nginx-proxy:
        build: .
        ports:
            - 80:80
            - 443:443
        networks:
            - net-proxy
        volumes:
            - conf:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - dhparam:/etc/nginx/dhparam
            - certs:/etc/nginx/certs:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
        labels:
            - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        volumes:
            - conf:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - dhparam:/etc/nginx/dhparam
            - certs:/etc/nginx/certs:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment: 
            DEFAULT_EMAIL: "contact@alexismartial.fr"
        networks:
            - net-proxy
        depends_on:
            - nginx-proxy
        # self signed
        #  omgwtfssl:
        #    image: paulczar/omgwtfssl
        #    restart: "no"
        #    volumes:
        #      - certs:/certs
        #    environment:
        #      - SSL_SUBJECT=servhostname.local
        #      - CA_SUBJECT=my@example.com
        #      - SSL_KEY=/certs/servhostname.local.key
        #      - SSL_CSR=/certs/servhostname.local.csr
        #      - SSL_CERT=/certs/servhostname.local.crt
        #    networks:
        #      - proxy-tier
volumes:
    conf:
    vhost:
    html:
    dhparam:
    certs:

networks:
    net-proxy: