version: '2'

services:
    nginx-proxy:
        build: 
            context: .
            target: dev
        ports:
            - 80:80
        networks:
            - net-proxy
        volumes:
            - conf:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - dhparam:/etc/nginx/dhparam
            - /var/run/docker.sock:/tmp/docker.sock:ro       
volumes:
    conf:
    vhost:
    html:
    dhparam:

networks:
    net-proxy: