logoutput: stderr

# Interface interne (ce que les clients utilisent pour se connecter au proxy)
internal: 0.0.0.0 port = 1080

# Interface externe (vers laquelle Dante route les connexions)
external: eth0

# Utilisateurs système pour Dante
user.privileged: root
user.notprivileged: nobody

# Rotation externe en mode route (par défaut)
external.rotation: route

#
# 1) Règles CLIENT — qui peut utiliser le proxy
#

# Autoriser uniquement ton réseau interne Docker
client pass {
    from: 172.20.0.0/16 to: 0.0.0.0/0
}

# Bloquer tout le reste
client block {
    from: 0.0.0.0/0 to: 0.0.0.0/0
}


#
# 2) Règles SOCKS — où le proxy a le droit d'envoyer les requêtes
#

# Autoriser uniquement vers ton réseau interne Docker
socks pass {
    from: 172.20.0.0/16 to: 172.20.0.0/16
    command: connect bind udpassociate
}

# Bloquer TOUT le trafic vers Internet
socks block {
    from: 0.0.0.0/0 to: 0.0.0.0/0
}