FROM alpine:latest

MAINTAINER SombrePigeon "contact@alexismartial.fr"

RUN apk update 

#RUN les installaaatisonssgdrxgvchq<cdesjvhysfdq

WORKDIR /root

RUN touch .ssh/authorized_keys

RUN mkdir repo

WORKDIR repo

RUN git init --bare



RUN apk add docker docker-compose

RUN pwd

#RUN git init --shared=true

