#!/bin/bash
TARGET="/home/webuser/deploy-folder"
GIT_DIR="/home/webuser/www.git"
BRANCH="main"

while read oldrev newrev ref
do
	# only checking out the $BRANCH
	if [ "$ref" = "refs/heads/$BRANCH" ];
	then
        echo "deploy activated"
		# run "make update" on the deploying 
		#make
	else
		echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
	fi
done